// templates/svelte-ts/ui/src/App.svelte
<script lang="ts">
  import logoSrc from "./assets/logo.png";
</script>

<main class="main">
  <img
    width="160"
    height="160"
    src={logoSrc}
    alt="javascript logo"
    class="logo"
  />
  <div class="content">
    <h1 class="title">
      Svelte&nbsp;<span class="logo-text">TS</span> template
    </h1>
    <p class="sub-title">Figma Plugin CLI</p>
  </div>
</main>

// templates/react-js/ui/src/App.jsx
import logoSrc from "./assets/logo.png";

function App() {
  return (
    <main className="main">
      <img
        width="160"
        height="160"
        src={logoSrc}
        alt="javascript logo"
        className="logo"
      />
      <div className="content">
        <h1 className="title">
          React&nbsp;<span className="logo-text">JS</span> template
        </h1>
        <p className="sub-title">Figma Plugin CLI</p>
      </div>
    </main>
  );
}

export default App;
